name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: rabits/qt:5.14-desktop

    steps:
    - name: switch user to root
      run: sudo -i
    - uses: actions/checkout@v2
      with: 
        path: project
        
    - name: qmake
      run: qmake
      working-directory: project
      
    - name: make
      run: make`
      working-directory: project
