name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    container:
      image: rabits/qt:5.14-desktop
      volumes:
        - project:/home/user
        - wksp:/__w/openocd-gui/openocd-gui/
      
    steps:
    - uses: actions/checkout@v2
        
    - name: qmake
      run: qmake
      
    - name: make
      run: make

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: openocdgui
        # Directory containing files to upload
        path: .
